import * as THREE from 'three';
import {GLTFLoader} from '../play/vendor/GLTFLoader.js';
import {OrbitControls} from '../play/vendor/OrbitControls.js';
import {addWorldDetails,australiaRegions,regionalScore,heatColor} from './world-details.js?v=storybook22';
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const palette={ideal:'#40a773',great:'#a9dc67',good:'#f4d45d',fair:'#f0a45c',avoid:'#e77c75'};
export async function createWorldMap(container,{data,iso=null,month=10,onSelect=()=>{},onCity=()=>{},onDismiss=()=>{},compact=false,flat=false,rounded=false}={}){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#78cbd5');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.className='map-canvas';renderer.domElement.setAttribute('aria-label','Drag to explore the '+'storybook'+' map. Use the buttons to zoom or select a place.');renderer.domElement.tabIndex=0;container.append(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#78cbd5');scene.add(new THREE.HemisphereLight('#e4f4ff','#7f9270',2));const sun=new THREE.DirectionalLight('#fff5dc',1.4);sun.position.set(-80,140,65);scene.add(sun);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-210,right:210,top:130,bottom:-130,near:1,far:500});sun.shadow.bias=-.0003;sun.shadow.normalBias=.06;
 const camera=new THREE.PerspectiveCamera(36,1,1,1800);camera.position.set(0,240,270);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.zoomSpeed=2.5;controls.minDistance=18;controls.maxDistance=1200;controls.minPolarAngle=.01;controls.maxPolarAngle=1.1;controls.enablePan=true;controls.mouseButtons={LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};controls.touches={ONE:THREE.TOUCH.PAN,TWO:THREE.TOUCH.DOLLY_PAN};controls.target.set(10,0,-12);if(flat){controls.enableRotate=false;controls.minPolarAngle=0;controls.maxPolarAngle=.001;}
 const labelLayer=document.createElement('div');labelLayer.className='map-labels';container.append(labelLayer);
 const labels=[],meshes=[],countryGroups=new Map(),featureMap=new Map();let selected=iso,mo=month,disposed=false,frame=0,tween=null;const byIso=new Map(data.map(r=>[r.iso,r]));
 function label(name,x,y,kind,rec){const el=document.createElement('button');el.className='map-label '+kind;el.innerHTML=kind==='city'?'<span class="dot"></span><span></span>':'';if(kind==='city')el.lastElementChild.textContent=name;else el.textContent=name;el.setAttribute('aria-label',kind==='city'?'Explore '+name:'Select '+name);el.addEventListener('click',()=>{if(kind==='city'){onCity(rec);focusCity(rec);}else{select(rec.iso,true);onSelect(rec.iso);}});labelLayer.append(el);labels.push({el,p:new THREE.Vector3(x,2,-y),kind,rec,priority:['Toronto','San Francisco','Tokyo','Manila','Kyoto','Sapporo','Naha','Cebu','Siargao'].includes(name)});}
 const response=await fetch(new URL('./assets/storybook-v1.glb.gz?v=storybook22',import.meta.url));if(!response.ok)throw new Error('World model unavailable');const bytes=await new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();const asset=await new GLTFLoader().parseAsync(bytes,'');
 const weather=[],blossoms=[],transport=[],oldSuns=[],borders=new Map();let growing=false,motion=!reduced(),regional=false,hovered=null,orbit=false,details,lastDraw=0;
 const tip=document.createElement('div');tip.className='map-hover';tip.hidden=true;container.append(tip);
 const info=document.createElement('section');info.className='sight-info';info.hidden=true;info.setAttribute('aria-live','polite');container.parentElement.append(info);
 function showSight(rec){select(rec.iso,false);info.replaceChildren();const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','Close place information');close.onclick=()=>{info.hidden=true;};const title=document.createElement('h2');title.textContent=rec.name;const description=document.createElement('p');description.textContent=rec.description||'Regional season estimate based on local travel seasons.';info.append(close,title,description);if(rec.window){const when=document.createElement('p');when.textContent='Typical window: '+rec.window;info.append(when);}if(rec.url){const a=document.createElement('a');a.href=rec.url;a.target='_blank';a.rel='noopener';a.textContent='Read the local guide ↗';info.append(a);}info.hidden=false;}
 scene.add(asset.scene);asset.scene.updateMatrixWorld(true);
 asset.scene.traverse(o=>{
  if(['boat','airplane'].includes(o.userData.role)){o.userData.start=o.position.clone();transport.push(o);}
  if(o.userData.role==='sun'){oldSuns.push(o);o.visible=false;}
  if(o.userData.role==='country')countryGroups.set(+o.userData.iso,o);
  if(o.userData.role==='blossom'){blossoms.push(o);o.userData.fullScale=o.scale.clone();o.userData.growth=1;}
  else if(o.userData.months&&o.userData.role!=='sun')weather.push(o);
  if(o.isMesh){o.castShadow=o.userData.role!=='ocean';o.receiveShadow=true;for(const m of Array.isArray(o.material)?o.material:[o.material]){m.roughness=.85;}}
 });
 for(const [id,group] of countryGroups){
  const bounds=new THREE.Box3().setFromObject(group);featureMap.set(id,{bounds});
  group.traverse(o=>{if(o.isMesh){o.userData.iso=id;for(const material of Array.isArray(o.material)?o.material:[o.material]){material.polygonOffset=true;material.polygonOffsetFactor=1;material.polygonOffsetUnits=2;}meshes.push(o);}});
  const rec=byIso.get(id),center=bounds.getCenter(new THREE.Vector3());
  if(rec)label(rec.name,rec.hub?.lng??center.x,rec.hub?.lat??-center.z,'country',rec);
 }
 const groundRay=new THREE.Raycaster();
 function ground(id,x,y){groundRay.set(new THREE.Vector3(x,80,-y),new THREE.Vector3(0,-1,0));const group=countryGroups.get(id);return group?(groundRay.intersectObject(group,true)[0]?.point.y??0):0;}
 const borderData=await fetch(new URL('./assets/borders.json?v=storybook22',import.meta.url)).then(r=>r.json());
 for(const [id,pts] of Object.entries(borderData)){if(!pts.length)continue;const geo=new THREE.BufferGeometry().setFromPoints(pts.map(p=>new THREE.Vector3(...p)));const line=new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:'#e2eee2',transparent:false,opacity:1,depthWrite:false,depthTest:false}));line.renderOrder=1;scene.add(line);line.userData.countries=id.split('-').map(Number);borders.set(id,line);}
 function addSight(rec,position){const el=document.createElement('button');el.className='map-label sight';const icon=rec.type==='beach'?'☂':rec.type==='storm'?'◉':'✦';el.textContent=icon+' '+rec.name;el.setAttribute('aria-label','Explore '+rec.name);el.onclick=()=>showSight(rec);labelLayer.append(el);labels.push({el,p:position,kind:'sight',rec,priority:rec.type==='storm'});}
 details=addWorldDetails(scene,{ground,data});
 // Draw inland borders as a map overlay, then let scenery cover them naturally.
 scene.traverse(o=>{if(o.isMesh&&!meshes.includes(o))o.renderOrder=2;});
 container.dataset.sightCount=String(details.items.filter(g=>!g.userData.months).length);
 if(!compact){const holder=container.parentElement.querySelector('.map-options-content');if(holder){const nav=document.createElement('select');nav.className='sight-picker';nav.setAttribute('aria-label','Explore a top sight');nav.innerHTML='<option value="">Explore a top sight…</option>';for(const g of details.items.filter(g=>!g.userData.months)){const o=document.createElement('option');o.value=g.userData.type;o.textContent=g.userData.name;nav.append(o);}nav.onchange=()=>{const g=details.items.find(g=>g.userData.type===nav.value);if(g){select(g.userData.iso,false);onSelect(g.userData.iso);onDismiss();move(new THREE.Vector3(g.position.x+(container.clientWidth>=600?1:0),0,g.position.z),20);showSight(g.userData);holder.closest('details').open=false;}};holder.append(nav);}}

 for(const sun of oldSuns)details.makeSun(sun.getWorldPosition(new THREE.Vector3()),Array.from(sun.userData.months));

 const australiaMeshes=[];countryGroups.get(36)?.traverse(o=>{if(o.isMesh){o.geometry=o.geometry.clone();o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();australiaMeshes.push(o);}});

 for(const rec of data)for(const city of rec.cities||[])label(city.name,city.lng,city.lat,'city',{...city,iso:rec.iso});
 for(const l of labels){groundRay.set(new THREE.Vector3(l.p.x,80,l.p.z),new THREE.Vector3(0,-1,0));const group=countryGroups.get(l.rec.iso);if(group){const hit=groundRay.intersectObject(group,true)[0];if(hit)l.p.y=hit.point.y+1;}if(l.kind==='city'){for(const sight of details.items){if(sight.userData.iso===l.rec.iso&&!sight.userData.months&&Math.hypot(l.p.x-sight.position.x,l.p.z-sight.position.z)<.4){sight.updateMatrixWorld(true);l.p.y=Math.max(l.p.y,new THREE.Box3().setFromObject(sight).max.y+.35);}}}}
 function colorCountries(){
  for(const [id,group] of countryGroups){const band=byIso.get(id)?.months[mo]?.band;const c=new THREE.Color(band?palette[band.key]:'#bdcddd');
   group.traverse(o=>{if(!o.isMesh)return;for(const m of Array.isArray(o.material)?o.material:[o.material]){
    m.emissive?.set(id===selected?'#e9d9a0':'#000000');m.emissiveIntensity=id===selected?.13:0;if(/Monthly heat|Heatmap facet|No climate data/.test(m.name)){const factor=m.name.match(/facet (\d*\.?\d+)/);m.color.copy(c).multiplyScalar(factor?+factor[1]:1);}
   }});
  }
  for(const o of weather)o.visible=Array.from(o.userData.months).includes(mo+1);
  for(const o of blossoms){o.userData.target=mo===2||mo===3?1:.001;if(reduced()){o.userData.growth=o.userData.target;o.scale.copy(o.userData.fullScale).multiplyScalar(o.userData.growth);}else growing=true;}
  for(const o of australiaMeshes){const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){m.vertexColors=regional;if(regional)m.color.set('#ffffff');m.needsUpdate=true;}if(regional){const pos=o.geometry.attributes.position,col=[];for(let i=0;i<pos.count;i++){const v=new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(o.matrixWorld),c=heatColor(regionalScore(v.x,-v.z,mo));col.push(c.r,c.g,c.b);}o.geometry.setAttribute('color',new THREE.Float32BufferAttribute(col,3));}}
  for(const [id,line] of borders){line.material.color.set(line.userData.countries.includes(selected)?'#fff8c7':'#e2eee2');line.material.opacity=1;}
  container.dataset.borderPairs=String(borders.size);container.dataset.month=String(mo);container.dataset.model='storybook-v1';container.dataset.regional=String(regional);
 }
 function updateLabels(){
  const occupied=[],distance=camera.position.distanceTo(controls.target),w=container.clientWidth,h=container.clientHeight;
  // Keep the whole-world view clear, including the selected country label.
  labelLayer.hidden=distance>=220;
  if(labelLayer.hidden)return;
  labelLayer.style.opacity=String(THREE.MathUtils.clamp((220-distance)/40,0,1));
  if(!compact){const r=container.getBoundingClientRect();container.parentElement.querySelectorAll('.world-tools,.country-panel,.world-months,.sight-info,.map-options[open] .map-options-content').forEach(el=>{if(el.hidden)return;const b=el.getBoundingClientRect();occupied.push([b.left-r.left,b.top-r.top,b.right-r.left,b.bottom-r.top]);});}
  for(const l of labels.slice().sort((a,b)=>Number(b.kind==='country'&&b.rec.iso===selected)*10+Number(b.priority)-Number(a.kind==='country'&&a.rec.iso===selected)*10-Number(a.priority))){
   let show=l.kind==='sight'?distance<125&&(!l.rec.months||l.rec.months.includes(mo+1))&&(l.rec.type!=='region'||regional):l.kind==='city'?(distance<([124,840].includes(l.rec.iso)&&l.rec.iso===selected?180:95)&&(!compact||l.rec.iso===selected)):distance>=95||(l.rec.iso===selected&&!l.rec.cities?.length);
   if(l.rec.type==='beach'&&distance>75)show=false;
   if(l.kind==='city'&&distance>65&&!l.priority&&!([124,840].includes(l.rec.iso)&&l.rec.iso===selected))show=false;
   const p=l.p.clone();if(flat)p.y=.9;p.project(camera);
   show&&=p.z>-1&&p.z<1&&p.x>-1&&p.x<1&&p.y>-1&&p.y<1;
   // Measure every label in CSS pixels before hiding it, including after font or viewport changes.
   l.el.hidden=false;l.el.style.visibility='hidden';
   const ww=l.el.getBoundingClientRect().width,hh=l.el.getBoundingClientRect().height;
   const sx=(p.x+1)*w/2,sy=(1-p.y)*h/2,box=[sx-ww/2,sy-hh,sx+ww/2,sy+8];
   if(box[0]<8||box[2]>w-8||box[1]<8||box[3]>h-8)show=false;
   if(show&&occupied.some(b=>box[0]<b[2]+10&&box[2]>b[0]-10&&box[1]<b[3]+10&&box[3]>b[1]-10))show=false;
   l.el.hidden=!show;if(!show)continue;
   occupied.push(box);l.el.style.visibility='';l.el.style.left=sx+'px';l.el.style.top=sy+'px';
   l.el.classList.toggle('active',l.kind==='country'&&l.rec.iso===selected);
   if(l.kind==='city'){const b=l.rec.months[mo].band;l.el.querySelector('.dot').textContent=Math.round(l.rec.months[mo].score);l.el.style.setProperty('--weather',palette[b.key]);l.el.setAttribute('aria-label',l.rec.name+': weather rating '+Math.round(l.rec.months[mo].score)+' out of 100, '+b.label+' in '+['January','February','March','April','May','June','July','August','September','October','November','December'][mo]);}
  }
 }

 function render(now=performance.now()){frame=0;if(disposed)return;if(motion&&!tween&&!growing&&now-lastDraw<33){invalidate();return;}lastDraw=now;if(tween){const now=performance.now(),t=Math.min(1,(now-tween.start)/650),v=1-(1-t)**4;camera.position.lerpVectors(tween.from,tween.to,v);controls.target.lerpVectors(tween.targetFrom,tween.targetTo,v);if(t===1)tween=null;controls.update();}if(growing){growing=false;for(const o of blossoms){const d=o.userData.target-o.userData.growth;o.userData.growth+=Math.abs(d)<.002?d:d*.1;o.scale.copy(o.userData.fullScale).multiplyScalar(o.userData.growth);o.visible=o.userData.growth>.002;if(Math.abs(d)>=.002)growing=true;}}constrain();const distance=camera.position.distanceTo(controls.target);details.update(mo,distance,now/1000,motion,camera);if(motion)transport.forEach((o,i)=>{o.position.copy(o.userData.start);o.position.x+=Math.sin(now/1000*.035+i)*2;o.position.z+=Math.cos(now/1000*.028+i)*.6;});container.dataset.camera=JSON.stringify({distance:+distance.toFixed(2),x:+controls.target.x.toFixed(2),z:+controls.target.z.toFixed(2),height:+camera.position.y.toFixed(2)});renderer.render(scene,camera);updateLabels();if(tween||growing||motion&&!document.hidden)invalidate();}
 function invalidate(){if(!frame&&!disposed)frame=requestAnimationFrame(render);}
 function move(target,distance){const angle=distance>200?1.45:.90;const to=target.clone().add(new THREE.Vector3(0,distance*Math.sin(angle),distance*Math.cos(angle)));if(reduced()){camera.position.copy(to);controls.target.copy(target);controls.update();}else tween={from:camera.position.clone(),to,targetFrom:controls.target.clone(),targetTo:target,start:performance.now()};invalidate();}
 function select(id,focus=true){selected=id;colorCountries();if(focus){const f=featureMap.get(id);if(f){const c=f.bounds.getCenter(new THREE.Vector3()),sz=f.bounds.getSize(new THREE.Vector3());let d=Math.max(sz.x/(container.clientWidth/container.clientHeight),sz.z)*2.3;d=Math.max(d,24);if(id===840){c.set(-98,0,-38);d=compact?100:120;}if(id===124){c.set(-102,0,-56);d=compact?105:125;}if(id===392){c.set(136,0,-35);d=compact?56:68;}if(id===608){c.set(122,0,-12.5);d=compact?44:53;}if(!compact&&container.clientWidth>=700)c.x-=d*.2;if(!compact&&container.clientWidth<700){c.z+=d*.06;d*=1.15;}move(c,d);}}invalidate();}
 function focusCity(c){move(new THREE.Vector3(c.lng,0,-c.lat),compact?17:23);}
 function constrain(){const old=controls.target.clone(),d=camera.position.distanceTo(old),halfHeight=d*Math.tan(Math.PI/10),limitX=Math.max(0,180-halfHeight*camera.aspect*.8),limitZ=Math.max(0,76-halfHeight*.8);controls.target.x=THREE.MathUtils.clamp(old.x,-limitX,limitX);controls.target.z=THREE.MathUtils.clamp(old.z,-10-limitZ,-10+limitZ);controls.target.y=0;camera.position.add(controls.target.clone().sub(old));camera.position.y=Math.max(camera.position.y,6);camera.lookAt(controls.target);}
 function resize(){const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();invalidate();}
 function zoom(factor){tween=null;const offset=camera.position.clone().sub(controls.target);offset.setLength(THREE.MathUtils.clamp(offset.length()*factor,controls.minDistance,controls.maxDistance));camera.position.copy(controls.target).add(offset);controls.update();constrain();invalidate();}
 // Trackpad pinch arrives as ctrl+wheel. Own this gesture only inside the map.
 const wheel=e=>{if(e.target.closest('.map-mini-controls'))return;e.preventDefault();e.stopImmediatePropagation();const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?container.clientHeight:1);zoom(Math.exp(THREE.MathUtils.clamp(delta,-100,100)*(e.ctrlKey?.018:.006)));};
 container.addEventListener('wheel',wheel,{passive:false,capture:true});
 const gesture=e=>e.preventDefault();container.addEventListener('gesturestart',gesture,{passive:false});
 const resume=()=>{if(!document.hidden)invalidate();};document.addEventListener('visibilitychange',resume);
 const ro=new ResizeObserver(resize);ro.observe(container);controls.addEventListener('change',invalidate);controls.addEventListener('start',()=>{tween=null;});
 const ray=new THREE.Raycaster();let down;
 function hover(id,e){if(hovered!==id){for(const [key,g] of countryGroups)g.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material]){m.emissive?.set(key===id?'#b5ddc6':key===selected?'#e9d9a0':'#000000');m.emissiveIntensity=key===id?.22:key===selected?.13:0;}});for(const [key,b] of borders){b.material.color.set(b.userData.countries.includes(id)?'#fffef0':b.userData.countries.includes(selected)?'#fff8c7':'#e2eee2');b.material.opacity=1;}hovered=id;container.dataset.hover=String(id??'');invalidate();}renderer.domElement.style.cursor=id?'pointer':orbit?'grab':'grab';tip.hidden=!id;if(id){tip.textContent=byIso.get(id)?.name||countryGroups.get(id)?.userData.country||'Country';tip.style.left=Math.min(container.clientWidth-140,e.offsetX+14)+'px';tip.style.top=Math.max(10,e.offsetY-30)+'px';}}
 renderer.domElement.addEventListener('pointermove',e=>{if(e.buttons)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const poi=ray.intersectObjects(details.interactive.filter(o=>o.parent.visible),false)[0];hover(ray.intersectObjects(meshes,false)[0]?.object.userData.iso??null,e);if(poi){renderer.domElement.style.cursor='pointer';tip.hidden=false;tip.textContent=poi.object.userData.sight.name;tip.style.left=Math.min(container.clientWidth-180,e.offsetX+14)+'px';tip.style.top=Math.max(10,e.offsetY-30)+'px';}});
 renderer.domElement.addEventListener('pointerleave',()=>hover(null,{}));
 renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const sightHit=ray.intersectObjects(details.interactive.filter(o=>o.parent.visible),false)[0];if(sightHit){showSight(sightHit.object.userData.sight);return;}const hit=ray.intersectObjects(meshes,false)[0];if(hit&&byIso.has(hit.object.userData.iso)){select(hit.object.userData.iso,false);onSelect(hit.object.userData.iso);}else{info.hidden=true;onDismiss();}});
 renderer.domElement.addEventListener('keydown',e=>{const amount=camera.position.distanceTo(controls.target)*.06,delta=new THREE.Vector3();if(e.key==='ArrowLeft')delta.x=-amount;else if(e.key==='ArrowRight')delta.x=amount;else if(e.key==='ArrowUp')delta.z=-amount;else if(e.key==='ArrowDown')delta.z=amount;else return;e.preventDefault();controls.target.add(delta);camera.position.add(delta);controls.update();invalidate();});
 if(compact){const nav=document.createElement('div');nav.className='map-mini-controls';nav.innerHTML='<button aria-label="Zoom in on city map">+</button><button aria-label="Zoom out on city map">−</button><button aria-label="Reset country view">↺</button>';nav.children[0].onclick=()=>{zoom(.65);};nav.children[1].onclick=()=>{zoom(1.5);};nav.children[2].onclick=()=>select(selected,true);container.append(nav);}
 colorCountries();resize();if(iso)select(iso,true);else move(new THREE.Vector3(-15,0,-12),Math.max(410,370/(2*Math.tan(Math.PI/10)*camera.aspect)));container.classList.add('loaded');const requestedCity=byIso.get(iso)?.cities?.find(c=>c.name===new URLSearchParams(location.search).get('city'));if(requestedCity)focusCity(requestedCity);const requestedSight=new URLSearchParams(location.search).get('sight');const initialSight=details.items.find(g=>g.userData.type===requestedSight);if(initialSight){onDismiss();move(new THREE.Vector3(initialSight.position.x+(container.clientWidth>=600?1:0),0,initialSight.position.z),20);showSight(initialSight.userData);}
 return {select,focusCity,setMotion(value){motion=value&&!reduced();invalidate();},setRegional(value){regional=value;colorCountries();invalidate();},setOrbit(value){orbit=value;controls.mouseButtons.LEFT=value?THREE.MOUSE.ROTATE:THREE.MOUSE.PAN;controls.touches.ONE=value?THREE.TOUCH.ROTATE:THREE.TOUCH.PAN;controls.touches.TWO=value?THREE.TOUCH.DOLLY_ROTATE:THREE.TOUCH.DOLLY_PAN;container.dataset.dragMode=value?'orbit':'pan';},topView(){tween=null;const d=camera.position.distanceTo(controls.target);camera.position.copy(controls.target).add(new THREE.Vector3(0,d,.01));controls.update();invalidate();},setMonth(m){mo=m;colorCountries();invalidate();},world(){info.hidden=true;move(new THREE.Vector3(-15,0,-12),Math.max(410,370/(2*Math.tan(Math.PI/10)*camera.aspect)));},zoom,rotate(){const v=camera.position.clone().sub(controls.target);v.applyAxisAngle(new THREE.Vector3(0,1,0),Math.PI/6);camera.position.copy(controls.target).add(v);controls.update();invalidate();},dispose(){disposed=true;document.removeEventListener('visibilitychange',resume);info.remove();tip.remove();container.removeEventListener('wheel',wheel,true);container.removeEventListener('gesturestart',gesture);ro.disconnect();controls.dispose();renderer.dispose();if(frame)cancelAnimationFrame(frame);scene.traverse(o=>{o.geometry?.dispose();for(const m of o.material?(Array.isArray(o.material)?o.material:[o.material]):[])m.dispose();});}};
}
