const cities=require('../climate/italy.json');
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

module.exports=function italyRegions(){
 for(const city of cities){
  if(!Number.isFinite(city.lat)||!Number.isFinite(city.lng)||!city.source?.url||!['hi','lo','pr'].every(key=>city[key]?.length===12&&city[key].every(Number.isFinite)))throw Error('Italy climate missing: '+city.name);
  for(let m=0;m<12;m++)if(city.hi[m]<city.lo[m]||city.pr[m]<0)throw Error('Italy climate invalid: '+city.name+' '+m);
 }
 const rows=months.map((month,m)=>`<tr><th scope="row">${month}</th>${cities.map(city=>`<td>${Math.round(city.hi[m])}°C<br><small>${Math.round(city.pr[m])} mm rain</small></td>`).join('')}</tr>`).join('');
 return `<section class="guide-section" id="regions"><div class="wrap"><h2>Italy weather, city by city</h2><p>The score above uses Rome. Compare five other cities before you choose a month.</p><p class="disc">Swipe the table sideways on a small screen.</p><p id="italy-weather-caption"><strong>Average daytime high and monthly rain, 2001–2020</strong></p><div class="table-scroll"><table class="weather-table" aria-labelledby="italy-weather-caption"><thead><tr><th scope="col">Month</th>${cities.map(city=>`<th scope="col">${esc(city.name)}<small>${esc(city.region)}</small></th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div><p>Palermo has milder winter days than Milan. July is hot in Rome, Naples and Palermo.</p><p>These city estimates cannot describe the Alps, every coast or sea conditions.</p><details class="guide-sources"><summary>Sources and weather notes</summary><p>NASA POWER / MERRA-2 estimates use daily data from 2001–2020. Highs are average daily highs; rain is the average monthly total. This is gridded climate data, not station readings or a forecast. The Rome score above uses a separate weather input.</p><p>${cities.map(city=>`<a href="${esc(city.source.url)}">${esc(city.name)} data</a>`).join(' · ')} · <a href="https://www.italia.it/en/italy/seasons">Italy tourism season guide</a> · <a href="https://www.italia.it/en/italy/grandi-destinazioni-italiane">Five city destinations</a> · <a href="https://www.italia.it/en/sicily/palermo">Palermo tourism</a> · Checked October 2026</p></details></div></section>`;
};
